table dim_customers
	lineageTag: 82a74df9-49f2-43a9-b957-2e0788c3e409

	column customer_id
		dataType: string
		lineageTag: 1d79740e-369a-49cb-9591-5653c2fdd523
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_unique_id
		dataType: string
		lineageTag: 1b141f50-d5f7-4455-bce2-5b7421c52085
		summarizeBy: none
		sourceColumn: customer_unique_id

		annotation SummarizationSetBy = Automatic

	column customer_zip_code_prefix
		dataType: string
		lineageTag: 85cc9f95-9251-497f-a5a5-c0651225606b
		summarizeBy: none
		sourceColumn: customer_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column customer_city
		dataType: string
		lineageTag: 0b5aa3b7-b69e-4c09-9cb0-ce8664b1fbdb
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

	column customer_state
		dataType: string
		lineageTag: cbd0b562-036f-45c6-a763-3969c514f4d5
		summarizeBy: none
		sourceColumn: customer_state

		annotation SummarizationSetBy = Automatic

	column 'Orders Per Customer' = ```
			
			VAR DeliveredOrderCount = 
			    CALCULATE(
			        DISTINCTCOUNT(fact_sales[order_id]),
			        ALLEXCEPT(dim_customers, dim_customers[customer_unique_id]),
			        dim_orders_payments_reviews[order_status] = "delivered"
			    )
			RETURN 
			    IF(ISBLANK(DeliveredOrderCount), 0, DeliveredOrderCount)
			```
		formatString: 0
		lineageTag: 24d92ea5-1527-473f-8937-ebaa82c842fc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Order_Segment = ```
			
			VAR OrderCount = dim_customers[Orders Per Customer]
			RETURN 
			    SWITCH(
			        TRUE(),
			        OrderCount = 0, "0 Order",
			        OrderCount = 1, "1 Order",
			        OrderCount = 2, "2 Orders",
			        OrderCount >= 3, "3+ Orders",
			        "Unknown"
			    )
			```
		lineageTag: 61f12e8f-6942-4ec9-ab9c-5c5c57d356d6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Customer_Type = ```
			
			VAR OrderCount = [Orders Per Customer]
			RETURN 
			    IF(OrderCount = 1, "Single Purchaser", IF(OrderCount = BLANK(),"Not Purchase","Repeat Purchaser"))
			```
		lineageTag: fe4e1ce6-432d-4faf-8361-6cff5a62a49a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column First_Category_Purchased = ```
			
			VAR CurrentCustomer = dim_customers[customer_unique_id]
			
			VAR FirstOrderDate = 
			    CALCULATE(
			        MIN(dim_orders_payments_reviews[order_purchase_timestamp]),
			        FILTER(
			            ALL(dim_orders_payments_reviews),
			            RELATED(dim_customers[customer_unique_id]) = CurrentCustomer &&
			            dim_orders_payments_reviews[order_status] = "Delivered"
			        )
			    )
			
			RETURN
			    CALCULATE(
			        FIRSTNONBLANK(dim_products[product_category_name], 1),
			        FILTER(
			            ALL(fact_sales),
			            RELATED(dim_customers[customer_unique_id]) = CurrentCustomer &&
			            RELATED(dim_orders_payments_reviews[order_purchase_timestamp]) = FirstOrderDate
			        )
			    )
			```
		lineageTag: 21d48819-1cec-4aee-8efc-e122757344f3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition dim_customers = m
		mode: import
		source =
				let
				    Source = MySQL.Database("127.0.0.1", "olist", [ReturnSingleDatabase=true]),
				    olist_dim_customers = Source{[Schema="olist",Item="dim_customers"]}[Data],
				    #"Capitalized Each Word" = Table.TransformColumns(olist_dim_customers,{{"customer_city", Text.Proper, type text}})
				in
				    #"Capitalized Each Word"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

